services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: trilha-poo-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: trilha-poo-pgsql
    environment:
      POSTGRES_DB: trilha_poo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: